#!/usr/bin/env python3
"""
One-time bootstrap: generate automation/overleaf_projects.txt from your account.

Overleaf has no API to list projects, so this reads the same data the dashboard
uses: it loads https://www.overleaf.com/project with your browser session cookie
and parses the `ol-projects` metadata blob. Run it locally whenever you want to
(re)generate the project list, then commit the file. The weekly job itself never
uses this cookie — it stays on the scoped, account-wide git token.

Getting the cookie (do NOT share it — it grants full access to your account):
  1. Log into overleaf.com in your browser.
  2. Open DevTools → Application (or Storage) → Cookies → https://www.overleaf.com
  3. Copy the VALUE of the cookie named `overleaf_session2`.

Run it:
  python3 automation/bootstrap_overleaf_projects.py
It will prompt for the cookie without echoing. (Alternatively, set the env var
OVERLEAF_SESSION to the cookie value first.) Add --all to include archived and
trashed projects too.

Stdlib only — no pip install needed. Requires Python 3.8+.
"""

from __future__ import annotations

import argparse
import getpass
import html
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

PROJECT_URL = "https://www.overleaf.com/project"
OUT_FILE = Path(__file__).resolve().parent / "overleaf_projects.txt"
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/125.0 Safari/537.36"
)

HEADER = """\
# Overleaf projects to include in the weekly report.
#
# One project per line:   <project-id>   <friendly label>
#
# This file was generated by automation/bootstrap_overleaf_projects.py, but you
# can hand-edit it freely: re-order, rename labels, or delete projects you don't
# want reported on. Re-run the bootstrap any time to refresh from your account.
#
# Authentication for the weekly job uses the account-wide OVERLEAF_TOKEN secret —
# never put a token or cookie in this file (it is committed to the repo).
"""


def fetch_projects_html(cookie: str) -> str:
    req = urllib.request.Request(
        PROJECT_URL,
        headers={"Cookie": f"overleaf_session2={cookie}", "User-Agent": USER_AGENT},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            final_url = resp.geturl()
            body = resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        sys.exit(f"Request failed: HTTP {exc.code} {exc.reason}. Is the cookie valid?")
    except urllib.error.URLError as exc:
        sys.exit(f"Network error: {exc.reason}")
    if "/login" in final_url:
        sys.exit(
            "Redirected to the login page — the cookie is missing or expired.\n"
            "Grab a fresh `overleaf_session2` value from your browser and try again."
        )
    return body


def parse_projects(page_html: str) -> list[dict]:
    # Find the <meta name="ol-projects" ...> tag regardless of attribute order.
    meta = re.search(r'<meta[^>]*\bname="ol-projects"[^>]*>', page_html)
    if not meta:
        sys.exit(
            "Could not find the project list in the page. The cookie may be "
            "expired, or Overleaf changed its markup. Try a fresh cookie first."
        )
    content = re.search(r'\bcontent="([^"]*)"', meta.group(0))
    if not content:
        sys.exit("Found the projects tag but no content attribute — unexpected markup.")
    raw = html.unescape(content.group(1))
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        sys.exit(f"Failed to parse the project JSON: {exc}")
    return data if isinstance(data, list) else data.get("projects", [])


def clean_name(name: str) -> str:
    return re.sub(r"\s+", " ", (name or "").strip())


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate overleaf_projects.txt")
    ap.add_argument("--all", action="store_true",
                    help="include archived and trashed projects too")
    args = ap.parse_args()

    cookie = os.environ.get("OVERLEAF_SESSION", "").strip()
    if not cookie:
        cookie = getpass.getpass("Paste your overleaf_session2 cookie value: ").strip()
    if not cookie:
        sys.exit("No cookie provided.")

    projects = parse_projects(fetch_projects_html(cookie))

    rows: list[tuple[str, str]] = []
    skipped = 0
    for p in projects:
        if not args.all and (p.get("archived") or p.get("trashed")):
            skipped += 1
            continue
        pid = p.get("id") or p.get("_id")
        if not pid:
            continue
        rows.append((str(pid), clean_name(p.get("name", "")) or str(pid)))

    rows.sort(key=lambda r: r[1].lower())

    width = max((len(pid) for pid, _ in rows), default=24)
    lines = [HEADER, ""]
    lines += [f"{pid.ljust(width)}   {label}" for pid, label in rows]
    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {len(rows)} projects to {OUT_FILE}")
    if skipped:
        print(f"Skipped {skipped} archived/trashed (use --all to include them).")
    print("Review the file, then commit it.")


if __name__ == "__main__":
    main()
