#!/usr/bin/env python3
"""
One-time bootstrap: generate automation/overleaf_projects.txt from your account.

Overleaf has no API to list projects, so this reads the same data the dashboard
uses: it loads https://www.overleaf.com/project with your browser session cookie
and parses the `ol-projects` metadata blob. Run it locally whenever you want to
(re)generate the project list, then commit the file. The weekly job itself never
uses this cookie — it stays on the scoped, account-wide git token.

Getting the cookie (do NOT share it — it grants full access to your account):
  1. Log into overleaf.com in your browser.
  2. Open DevTools → Application (or Storage) → Cookies → https://www.overleaf.com
  3. Copy the VALUE of the cookie named `overleaf_session2`.

Run it:
  python3 automation/bootstrap_overleaf_projects.py
It will prompt for the cookie without echoing. (Alternatively, set the env var
OVERLEAF_SESSION to the cookie value first.) Add --all to include archived and
trashed projects too.

Stdlib only — no pip install needed. Requires Python 3.8+.
"""

from __future__ import annotations

import argparse
import getpass
import html
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

PROJECT_URL = "https://www.overleaf.com/project"
OUT_FILE = Path(__file__).resolve().parent / "overleaf_projects.txt"
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/125.0 Safari/537.36"
)

HEADER = """\
# Overleaf projects to include in the weekly report.
#
# One project per line:   <project-id>   <friendly label>
#
# This file was generated by automation/bootstrap_overleaf_projects.py, but you
# can hand-edit it freely: re-order, rename labels, or delete projects you don't
# want reported on. Re-run the bootstrap any time to refresh from your account.
#
# Authentication for the weekly job uses the account-wide OVERLEAF_TOKEN secret —
# never put a token or cookie in this file (it is committed to the repo).
"""


def fetch_projects_html(cookie: str) -> str:
    req = urllib.request.Request(
        PROJECT_URL,
        headers={"Cookie": f"overleaf_session2={cookie}", "User-Agent": USER_AGENT},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            final_url = resp.geturl()
            body = resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        sys.exit(f"Request failed: HTTP {exc.code} {exc.reason}. Is the cookie valid?")
    except urllib.error.URLError as exc:
        sys.exit(f"Network error: {exc.reason}")
    if "/login" in final_url:
        sys.exit(
            "Redirected to the login page — the cookie is missing or expired.\n"
            "Grab a fresh `overleaf_session2` value from your browser and try again."
        )
    return body


# Overleaf has used different names/containers for the project blob over time.
# Newer dashboards use `ol-prefetchedProjectsBlob` ({"projects": [...]}); older
# ones used `ol-projects` (a bare list). The blob may live in a <meta content="">
# (HTML-escaped JSON) or a <script>...</script> (raw JSON).
CANDIDATE_KEYS = ("ol-prefetchedProjectsBlob", "ol-projects")


def _extract_json_blob(page_html: str, key: str) -> str | None:
    meta = re.search(r'<meta[^>]*\b(?:name|id)="' + re.escape(key) + r'"[^>]*>', page_html)
    if meta:
        content = re.search(r'\bcontent="([^"]*)"', meta.group(0))
        if content:
            return html.unescape(content.group(1))
    script = re.search(
        r'<script[^>]*\b(?:id|name)="' + re.escape(key) + r'"[^>]*>(.*?)</script>',
        page_html,
        re.DOTALL,
    )
    if script:
        return script.group(1).strip()
    return None


def _diagnose_and_exit(page_html: str) -> None:
    names = sorted(set(re.findall(r'(?:name|id)="(ol-[^"]+)"', page_html)))
    looks_login = bool(re.search(r'name="ol-csrfToken"', page_html)) and not any(
        "roject" in n for n in names
    )
    lines = ["Could not find the project list in the page."]
    if looks_login or not names:
        lines.append(
            "The page looks like the login page — the cookie is missing or "
            "expired. Grab a FRESH overleaf_session2 value and retry."
        )
    else:
        lines.append("Overleaf's markup may have changed. The ol-* tags present are:")
        lines.append("  " + ", ".join(names))
        lines.append(
            "Re-run with --debug (saves the page to automation/_work/"
            "overleaf_debug.html) and share the tag names above."
        )
    sys.exit("\n".join(lines))


def parse_projects(page_html: str) -> list[dict]:
    for key in CANDIDATE_KEYS:
        raw = _extract_json_blob(page_html, key)
        if not raw:
            continue
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            continue
        projects = data.get("projects") if isinstance(data, dict) else data
        if isinstance(projects, list):
            return projects
    _diagnose_and_exit(page_html)
    return []  # unreachable; _diagnose_and_exit raises


def clean_name(name: str) -> str:
    return re.sub(r"\s+", " ", (name or "").strip())


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate overleaf_projects.txt")
    ap.add_argument("--all", action="store_true",
                    help="include archived and trashed projects too")
    ap.add_argument("--debug", action="store_true",
                    help="save the fetched dashboard HTML for inspection")
    args = ap.parse_args()

    cookie = os.environ.get("OVERLEAF_SESSION", "").strip()
    if not cookie:
        cookie = getpass.getpass("Paste your overleaf_session2 cookie value: ").strip()
    if not cookie:
        sys.exit("No cookie provided.")

    page = fetch_projects_html(cookie)
    if args.debug:
        dbg = Path(__file__).resolve().parent / "_work" / "overleaf_debug.html"
        dbg.parent.mkdir(parents=True, exist_ok=True)
        dbg.write_text(page, encoding="utf-8")
        print(f"Saved page to {dbg} ({len(page)} bytes)")
    projects = parse_projects(page)

    rows: list[tuple[str, str]] = []
    skipped = 0
    for p in projects:
        if not args.all and (p.get("archived") or p.get("trashed")):
            skipped += 1
            continue
        pid = p.get("id") or p.get("_id")
        if not pid:
            continue
        rows.append((str(pid), clean_name(p.get("name", "")) or str(pid)))

    rows.sort(key=lambda r: r[1].lower())

    width = max((len(pid) for pid, _ in rows), default=24)
    lines = [HEADER, ""]
    lines += [f"{pid.ljust(width)}   {label}" for pid, label in rows]
    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {len(rows)} projects to {OUT_FILE}")
    if skipped:
        print(f"Skipped {skipped} archived/trashed (use --all to include them).")
    print("Review the file, then commit it.")


if __name__ == "__main__":
    main()
